"""remove cascade

Revision ID: 0171883282fa
Revises: fd518f85769b
Create Date: 2022-04-28 11:28:26.675993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0171883282fa'
down_revision = 'fd518f85769b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('my_meal_plan_recipe_id_fkey', 'my_meal_plan', type_='foreignkey')
    op.create_foreign_key(None, 'my_meal_plan', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'my_meal_plan', type_='foreignkey')
    op.create_foreign_key('my_meal_plan_recipe_id_fkey', 'my_meal_plan', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
