"""empty message

Revision ID: 26ba8caf7f07
Revises: c49eb5babcc7
Create Date: 2022-04-21 01:14:06.968048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ba8caf7f07'
down_revision = 'c49eb5babcc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image_url', sa.String(length=100), nullable=True))
    op.alter_column('recipe', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('recipe', 'instruction',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.drop_column('recipe', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('recipe', 'instruction',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recipe', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('recipe', 'image_url')
    # ### end Alembic commands ###
