"""cascade?

Revision ID: 2e8f4930f495
Revises: af90a22d9d29
Create Date: 2022-04-28 03:05:05.198806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8f4930f495'
down_revision = 'af90a22d9d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('my_meal_plan_recipe_id_fkey', 'my_meal_plan', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('my_meal_plan_recipe_id_fkey', 'my_meal_plan', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
