"""MyRecipes

Revision ID: 75e360c469f7
Revises: 1cc4497a2cb6
Create Date: 2022-04-21 16:25:11.742221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e360c469f7'
down_revision = '1cc4497a2cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('reference', sa.String(length=100), nullable=True))
    op.add_column('recipe', sa.Column('time', sa.String(length=35), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'time')
    op.drop_column('recipe', 'reference')
    # ### end Alembic commands ###
