"""empty message

Revision ID: c49eb5babcc7
Revises: eb2b9fcf3abc
Create Date: 2022-04-19 22:51:25.981327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49eb5babcc7'
down_revision = 'eb2b9fcf3abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_image_key', 'recipe', type_='unique')
    op.drop_constraint('recipe_recipe_name_key', 'recipe', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('recipe_recipe_name_key', 'recipe', ['recipe_name'])
    op.create_unique_constraint('recipe_image_key', 'recipe', ['image'])
    # ### end Alembic commands ###
