"""empty message

Revision ID: eb2b9fcf3abc
Revises: e3b49376ba79
Create Date: 2022-04-19 22:50:11.487173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2b9fcf3abc'
down_revision = 'e3b49376ba79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('recipe_name', sa.String(length=50), nullable=False))
    op.drop_constraint('recipe_name_key', 'recipe', type_='unique')
    op.create_unique_constraint(None, 'recipe', ['recipe_name'])
    op.drop_column('recipe', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recipe', type_='unique')
    op.create_unique_constraint('recipe_name_key', 'recipe', ['name'])
    op.drop_column('recipe', 'recipe_name')
    # ### end Alembic commands ###
